name: Helm Chart Release Template

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      repo_url:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm package ${{ inputs.chart_path }} -d packaged
          helm repo index packaged --url ${{ inputs.repo_url }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packaged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
